parameters:
  - name: pool
    displayName: 'Agent Pool'
    type: string
    default: 'Azure Pipelines'
    values:
      - 'Azure Pipelines'
      - 'Self-hosted'

trigger:
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
      - master
      - main

resources:
  repositories:
    - repository: templates
      endpoint: thenoobsbr
      type: github
      name: TheNoobsBr/Azure-Templates
      ref: refs/tags/2.2.0

variables:
  - template: variables.yml

stages:
  - template: templates/versioning/calculate_sem_version.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
  - template: templates/csharp/library_build.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
  - template: templates/nuget/publish_package.yml@templates
    parameters:
      pool: ${{ parameters.pool }}